# Generated by Django 5.2.14 on 2026-06-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('audio_filename', models.CharField(blank=True, max_length=255, null=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('audio_risk', models.FloatField(blank=True, null=True)),
                ('text_risk', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField()),
                ('verdict', models.CharField(choices=[('SAFE', 'Safe'), ('SUSPICIOUS', 'Suspicious'), ('CRITICAL FRAUD', 'Critical Fraud')], default='SAFE', max_length=20)),
                ('recommendation', models.TextField(blank=True)),
                ('processing_ms', models.IntegerField(default=0)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Analysis Record',
                'verbose_name_plural': 'Analysis Records',
                'ordering': ['-created_at'],
            },
        ),
    ]
